In [1]:
import numpy as np # type: ignore

# Create a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:")
print(matrix)


Matrix:
[[1 2]
 [3 4]]


In [2]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Add matrices
result = matrix1 + matrix2
print("Matrix Addition:")
print(result)

Matrix Addition:
[[ 6  8]
 [10 12]]


In [3]:
# Multiply matrices
result = np.dot(matrix1, matrix2)
print("Matrix Multiplication:")
print(result)

Matrix Multiplication:
[[19 22]
 [43 50]]


In [4]:
# Transpose a matrix
transposed = matrix1.T
print("Original Matrix:")
print(matrix1)
print("Transposed Matrix:")
print(transposed)

Original Matrix:
[[1 2]
 [3 4]]
Transposed Matrix:
[[1 3]
 [2 4]]


In [9]:
# Calculate the determinant of a matrix
determinant = np.linalg.det(matrix1)
print('The matrix1 is:')
print(matrix1)
print("Determinant of matrix1:")
print(determinant)

The matrix1 is:
[[1 2]
 [3 4]]
Determinant of matrix1:
-2.0000000000000004


In [11]:
# Calculate the inverse of a matrix
inverse = np.linalg.inv(matrix1)
print("Original Matrix:")
print(matrix1)
print("Inverse of matrix1:")
print(inverse)
print("Product of matrix1 and its inverse:")
print(np.dot(matrix1, inverse))

Original Matrix:
[[1 2]
 [3 4]]
Inverse of matrix1:
[[-2.   1. ]
 [ 1.5 -0.5]]
Product of matrix1 and its inverse:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [6]:
# Calculate the adjoint of a matrix
adjoint = np.linalg.inv(matrix1) * determinant
print('Original Matrix:')
print(matrix1)
print("Adjoint of matrix1:")
print(adjoint)

Original Matrix:
[[1 2]
 [3 4]]
Adjoint of matrix1:
[[ 4. -2.]
 [-3.  1.]]
