In [2]:
import numpy as np # type: ignore

# Create a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:")
print(matrix)


Matrix:
[[1 2]
 [3 4]]


In [3]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Add matrices
result = matrix1 + matrix2
print("Matrix Addition:")
print(result)

Matrix Addition:
[[ 6  8]
 [10 12]]


In [4]:
# Multiply matrices
result = np.dot(matrix1, matrix2)
print("Matrix Multiplication:")
print(result)

Matrix Multiplication:
[[19 22]
 [43 50]]


In [5]:
# Transpose a matrix
transposed = matrix1.T
print("Original Matrix:")
print(matrix1)
print("Transposed Matrix:")
print(transposed)

Original Matrix:
[[1 2]
 [3 4]]
Transposed Matrix:
[[1 3]
 [2 4]]


In [6]:
# Calculate the determinant of a matrix
determinant = np.linalg.det(matrix1)
print('The matrix1 is:')
print(matrix1)
print("Determinant of matrix1:")
print(determinant)

The matrix1 is:
[[1 2]
 [3 4]]
Determinant of matrix1:
-2.0000000000000004


In [7]:
# Calculate the inverse of a matrix
inverse = np.linalg.inv(matrix1)
print("Original Matrix:")
print(matrix1)
print("Inverse of matrix1:")
print(inverse)
print("Product of matrix1 and its inverse:")
print(np.dot(matrix1, inverse))

Original Matrix:
[[1 2]
 [3 4]]
Inverse of matrix1:
[[-2.   1. ]
 [ 1.5 -0.5]]
Product of matrix1 and its inverse:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [8]:
# Calculate the adjoint of a matrix
adjoint = np.linalg.inv(matrix1) * determinant
print('Original Matrix:')
print(matrix1)
print("Adjoint of matrix1:")
print(adjoint)

Original Matrix:
[[1 2]
 [3 4]]
Adjoint of matrix1:
[[ 4. -2.]
 [-3.  1.]]


In [ ]:
import matplotlib.pyplot as plt  # type: ignore
import numpy as np  # type: ignore
# plot two graphs: left y=3x, right y=x^2

x = np.linspace(-10, 10, 100)
y1 = 3 * x
y2 = x ** 2
fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.plot(x, y1)
ax2.plot(x, y2)
ax1.set_title('y=3x')
ax2.set_title('y=x^2')
plt.show()

# save it to a png file
fig.savefig('plot.png')


In [10]:
# Using gradient descent to find the minimum of f(x) = x^2

def f(x):
  return x**2

# the gradient of f(x) can be conveniently calculated as:
def grad_f(x):
  return 2 * x

# Set an initial guess for x, learning rate, and convergence criteria
x = 10.0  # initial value
learning_rate = 0.1 # learning rate
max_iter = 100
tolerance = 1e-6

print("Iteration\t   x\t          f(x)\t          Gradient")
for i in range(max_iter):
  gradient = grad_f(x)
  print(f"{i+1:9d}\t {x:7.6f}\t {f(x):7.6f}\t {gradient:9.6f}")
  # Update x using gradient descent rule
  x_new = x - learning_rate * gradient
  if abs(x_new - x) < tolerance:
    x = x_new
    break
  x = x_new

print("\nConverged: x =", x, "with f(x) =", f(x))

Iteration	   x	          f(x)	          Gradient
        1	 10.000000	 100.000000	 20.000000
        2	 8.000000	 64.000000	 16.000000
        3	 6.400000	 40.960000	 12.800000
        4	 5.120000	 26.214400	 10.240000
        5	 4.096000	 16.777216	  8.192000
        6	 3.276800	 10.737418	  6.553600
        7	 2.621440	 6.871948	  5.242880
        8	 2.097152	 4.398047	  4.194304
        9	 1.677722	 2.814750	  3.355443
       10	 1.342177	 1.801440	  2.684355
       11	 1.073742	 1.152922	  2.147484
       12	 0.858993	 0.737870	  1.717987
       13	 0.687195	 0.472237	  1.374390
       14	 0.549756	 0.302231	  1.099512
       15	 0.439805	 0.193428	  0.879609
       16	 0.351844	 0.123794	  0.703687
       17	 0.281475	 0.079228	  0.562950
       18	 0.225180	 0.050706	  0.450360
       19	 0.180144	 0.032452	  0.360288
       20	 0.144115	 0.020769	  0.288230
       21	 0.115292	 0.013292	  0.230584
       22	 0.092234	 0.008507	  0.184467
       23	 0.073787	 0.005445	  0.147574
