# Week 09

## Assembing Functions

In some cases, we may want to define a function that is composed of other functions. For example, we can define a sigmoid function using the exponential function. 

###  Sigmoid Function

A sigmoid function is defined by the expression:

$$g(z) = \frac{1}{1+e^{-z}}$$

For any value of $z$, the sigmoid function will output a value between 0 and 1.

We can write a Python function to compute the sigmoid function. First, we will a function to calculate the exponential part: $$e^{-z}$$

### Exponential Function

In python, we can use the `np.exp()` function to calculate the exponential of a number. 


In [9]:

import numpy as np

print(np.exp(0))  # Should print 1.0

1.0


### Assembling the Functions

Next, we can integrate the exponential function into the sigmoid function:

$$ g(z) = \frac{1}{1+\text{np.exp}(-z)} $$

We need to replace `np.exp` with the actual function call to compute the exponential of `-z`.


In [10]:

import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# test

print(sigmoid(0))  # Should print 0.5

0.5


Here we use `np.exp()` to calculate the exponential of `-z` and then compute the sigmoid function. In this way, we do not need manually write the exponential function, we can directly use the built-in function from the numpy library and assemble it into the sigmoid function.


## Other useful `np` functions

### Log Function
We can use the `np.log()` function to calculate the natural logarithm of a number $log(x)$.


In [11]:
import numpy as np

print(np.log(1))  # Should print 0.0

0.0


### Dot Product Function

We can use the `np.dot()` function to calculate the dot product of two vectors or matrices. ($ \mathbf{a} \cdot \mathbf{b}$)

In [12]:
# import numpy as np
import numpy as np

# test: dot product [1, 2] . [3, 4] = 1*3 + 2*4 = 11
print(np.dot(np.array([1, 2]), np.array([3, 4])))  # Should print 11

11


### Sum Function

We can use the `np.sum()` function to calculate the sum of all elements in an array or along a specified axis. ($ \sum_{i=1}^{n} a_i$)

In [13]:
# import numpy as np
import numpy as np

# test: sum([1, 2, 3]) = 1 + 2 + 3 = 6
print(np.sum(np.array([1, 2, 3])))  # Should print 6

6


You will need these functions to assemble the custom functions for the PS 2.

### Random Number Generation
We can use the `np.random.rand()` function to generate random numbers. For example, `np.random.rand(3)` will generate a 1D array of 3 random numbers between 0 and 1.

In [17]:
import numpy as np
print(np.random.rand(3))  # Should print an array of 3 random numbers between 0 and 1

[0.38436615 0.38643049 0.97440937]


#### Random Seed
Try if you re-run the above command, you will get different random numbers each time. It is because the random number generator is seeded with the current time, so each time you run the command, it will generate a different set of random numbers. If you want to generate the same set of random numbers every time, you can set a seed using `np.random.seed(seed_value)

In [19]:
np.random.seed(0)

print (np.random.rand(3))  # Should print an array of 3 random numbers with a fixed seed

[0.5488135  0.71518937 0.60276338]


Now you should get the same set of random numbers every time you run the command.

### Threshold Function

We can define a threshold function that outputs 1 if the input is greater than or equal to a certain threshold, and 0 otherwise. It is useful for binary classification tasks.

$$ \text{threshold}(x, \text{threshold\_value}) =
\begin{cases}
1 & \text{if } x \geq \text{threshold\_value} \\
0 & \text{otherwise}
\end{cases}
$$

In [20]:
import numpy as np
np.random.seed(42)
x = np.random.rand(3)
print(x)  # Should print the same array of 3 random numbers with a fixed seed

# Initialize an array p with zeros of the same shape as x
p = np.zeros(x.shape, dtype=int)

# Use enumerate to get the correct index for each element in x
for i, x_i in enumerate(x):
  p[i] = int(x_i > 0.5) # if x_i > 0.5 then set p[i] to 1 else 0

print(p)  # Prints an array of 0s and 1s based on the condition

[0.37454012 0.95071431 0.73199394]
[0 1 1]
